## Put comments here that give an overall description of what your
## functions do

## makeCacheMatrix returns a list containing functions for getting and setting 
## a matrix as well as its inverse

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  get <- function() x
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  getinverse <- function() inv
  setinverse <- function(y) inv <<- y
  list(set = set,
       setinverse = setinverse,
       get = get,
       getinverse = getinverse)
}


## the cacheSolve function takes a cacheMatrix generated by the
## makeCacheMatrix function and returns the inverse
## Before solving, it will first attempt to find the cached inverse in 
## cacheMatrix

cacheSolve <- function(cacheMatrix, ...) {
  ## Return a matrix that is the inverse of 'cacheMatrix'
  m <- cacheMatrix$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    # since we have a cached matrix, return it instead of solving
    return(m)               
  }
  data <- cacheMatrix$get() # get the original matrix
  m <- solve(data, ...)     # invert it
  cacheMatrix$setinverse(m) # cache the inverse 
  m
}
